-- Drop tables if they exist to ensure a clean slate on each startup.
-- This is useful for development but should be used with caution.
DROP TABLE IF EXISTS todos;
DROP TABLE IF EXISTS users;

-- Create the 'users' table first because 'todos' has a foreign key to it.
CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username    VARCHAR(255) NOT NULL UNIQUE,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- Create the 'todos' table with a foreign key constraint to the 'users' table.
CREATE TABLE todos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title           VARCHAR(255) NOT NULL,
    description     VARCHAR(255),
    completed       BOOLEAN NOT NULL,
    user_id         BIGINT NOT NULL,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_todos_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);